import FooterElement from "@/components/FooterElement";
import "@/styles/global.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <FooterElement />
      </body>
    </html>
  );
}
